### ISSUE TITLE
Initial Launch Blank Window

### ISSUE THREAD

**Issue by the-narwhal** [flathub/io.frappe.books#1]
Initial launch after install from flathub produces a blank window.

system: Fedora 40, up to date.

$ flatpak run io.frappe.books
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: rpm
Gtk-Message: 10:55:09.941: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:55:09.941: Failed to load module "pk-gtk-module"
Gtk-Message: 10:55:09.942: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:55:09.942: Failed to load module "pk-gtk-module"
[3:1021/105509.953692:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1021/105509.953721:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
MESA: error: Failed to query drm device.
glx: failed to create dri3 screen
failed to load driver: iris

Let me know if any additional info is helpful to diagnose.

![image](https://github.com/user-attachments/assets/291ea7db-b7bd-4653-a986-ad4d5b66da51)

**Comment by kskarthik** [comment]
@bbhtt any clue about this!?

**Comment by bbhtt** [comment]
Sounds like a MESA or a driver issue, hard to say.

**Comment by kskarthik** [comment]
@01111010t please open the [flatseal app](https://flathub.org/apps/com.github.tchx84.Flatseal) & give frappe books this below permission & restart ?

![image](https://github.com/user-attachments/assets/00228555-ae15-42c8-ae71-2d04bce5c8ea)

**Comment by the-narwhal** [comment]
> @01111010t please open the [flatseal app](https://flathub.org/apps/com.github.tchx84.Flatseal) & give frappe books this below permission & restart ?
> 
> ![image](https://private-user-images.githubusercontent.com/11899221/381230175-00228555-ae15-42c8-ae71-2d04bce5c8ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjEwNzUsIm5iZiI6MTczMDIyMDc3NSwicGF0aCI6Ii8xMTg5OTIyMS8zODEyMzAxNzUtMDAyMjg1NTUtYWUxNS00MmM4LWFlNzEtMmQwNGJjZTVjOGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE2NTI1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMzIxZjdiNTk4NjQ0ZDE5MTVlMzkzMmFjMTM4MzkxODg5NTBhMzVlMTY2ZDIxMDQyNGQ5ZmZhY2E1OWQ2MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nVrsRKPjFm7LEE00MGBISrxr6TKqJCJ84y35QGi6u58)

Amusingly, I was poking around in flatseal to see if i could figure out a toggle to help and noticed this same one makes it work about 5 minutes ago.

![image](https://github.com/user-attachments/assets/a1b3e4c2-929b-4570-8d4e-81319f9c4371)

![image](https://github.com/user-attachments/assets/8ca57447-affd-49b4-9ed5-efb968077221)

**Comment by kskarthik** [comment]
@01111010t thank you for your debug help! a new release will be out asap!
